kind: Service
apiVersion: v1
metadata:
  name: user-manager
  labels:
    cluster: management
    component: user-manager
  namespace: nalej
spec:
  selector:
    cluster: management
    component: user-manager
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8920
    targetPort: 8920