###
# User Manager
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: user-manager
  name: user-manager
  namespace: nalej
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: user-manager
  template:
    metadata:
      labels:
        cluster: management
        component: user-manager
    spec:
      containers:
      - name: user-manager
        image: nalejregistry.azurecr.io/nalej/user-manager:VERSION
        imagePullPolicy: IfNotPresent
        args:
        - "run"
        - "--debug"
        - "--systemModelAddress=system-model.nalej:8800"
        - "--authxAddress=authx.nalej:8810"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
