###
# Application example
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: user-manager
  name: user-manager
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: user-manager
  template:
    metadata:
      labels:
        cluster: management
        component: user-manager
    spec:
      containers:
      - name: user-manager
        image: nalej/user-manager:VERSION
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: myregistrykey
