FROM node:8.12.0-alpine
COPY package.json package-lock.json ./

RUN npm i && mkdir -p /ng-app/src && mv ./node_modules ./ng-app
WORKDIR /ng-app

COPY *.json ./
COPY src/ src/.

RUN $(npm bin)/ng build
