export const LocalStorageKeys = {
    // Mocked views
    loginMock: 'login_mock',
    organizationMock: 'organization_mock',
    resourcesMock: 'resources_mock',
    clusterMock: 'cluster_mock',
    appsMock: 'apps_mock',
    profileMock: 'profile_mock',
    sidebarMock: 'sidebar_mock',
    notificationsMock: 'notifications_mock',
    userInfoMock: 'user_info_mock',
    userEditMock: 'user_edit_mock',
    clusterEditMock: 'cluster_edit_mock',
    addUserMock: 'add_user_mock',
    passwordMock: 'password_change_mock',
    addLabelMock: 'add_label_mock',
    devicesMock: 'devices_mock',
    addGroupMock: 'add_group_mock',
    configGroupMock: 'configuration_group_mock',
    createdGroupMock: 'group_created_mock',
    registerAppMock: 'register_app_mock',
    deployInstanceMock: 'deploy_instance_mock',
    registeredInfoMock: 'registered_info_mock',
    instanceInfoMock: 'instance_info_mock',
    serviceInstancesInfoMock: 'service_instances_info_mock',
    ruleInfoMock: 'rule_info_mock',
    serviceInfoMock: 'service_info_mock',
    infrastructureMock: 'infrastructure_mock',
    deviceInfoMock: 'device_info_mock',
    assetInfoMock: 'asset_info_mock',
    edgeControllerInfoMock: 'edge_controller_info_mock',
    installAgentMock: 'install_agent_mock',
    simpleLogMock: 'simple_log_mock',
    eicJoinTokenInfoMock: 'eic_join_token_info_mock',
    agentJoinTokenInfoMock: 'agent_join_token_info_mock',
    addConnectionsMock: 'add_connections_mock',
    advancedFilterOptions: 'advanced_filter_options',
    manageConnectionsMock: 'manage_connections_mock',

    // Data
    jwt: 'jwt',
    jwtData: 'jwt_data',
    userId: 'user_id',
    refreshToken: 'refresh_token',
    url: 'url'
};

