kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    cluster: management
    component: web
  namespace: nalej
spec:
  selector:
    cluster: management
    component: web
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32500
