kind: Service
apiVersion: v1
metadata:
  name: web
  labels:
    cluster: management
    component: web
  namespace: __NPH_NAMESPACE
spec:
  selector:
    cluster: management
    component: web
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http-web

